### ISSUE TITLE
Backend Server, as How?

### ISSUE THREAD

**Issue by zionnite** [appwrite/docs#236]
Hello, I just got to know about this particular service (AppWrite), how is a backend server if I still have to host it on digitalOcean.

**Comment by fbartels** [comment]
The idea of the project (as far as I understand) is to provide a self host able alternative to solutions like Googles Firebase. Self hosting the Backend is more work, than relying on a third party, but also gives more control.

If you want to use appwrite, but don't want to host the Backend, then https://appwrite.io/cloud could be interesting to you.

**Comment by zionnite** [comment]
> The idea of the project (as far as I understand) is to provide a self host able alternative to solutions like Googles Firebase. Self hosting the Backend is more work, than relying on a third party, but also gives more control.
> 
> If you want to use appwrite, but don't want to host the Backend, then https://appwrite.io/cloud could be interesting to you.

Thanks for this,
It make more sense now.

**Comment by zionnite** [comment]
Thank you very much Sir for your time, am still trying to figure out why appwrite it's better than other services like firebase etc.

If self hosting is more work, why should I use it?

Can it be hosted on an Apache Server? (Curious)


Using AppWrite, does it cut cost compared to firebase etc?


When I host AppWrite to digitocean, is that not going to cost me alot compare to firebase.?


How does infact AppWrite cut cost compared to other baas?


Thank you for your time and help

**Comment by fbartels** [comment]
> If self hosting is more work, why should I use it?

This is like learning to tailor your own clothes, vs buying them off the rack. Depending on what you want to achieve one could be superior to the other.

> Can it be hosted on an Apache Server? (Curious)

I don't think so.

> Using AppWrite, does it cut cost compared to firebase etc?

> When I host AppWrite to digitocean, is that not going to cost me alot compare to firebase.?

> How does infact AppWrite cut cost compared to other baas?

Depends. When using Appwrite you have to costs of the machines you are running it on, and of course the costs for your own time maintaining these installations. Compared to that a third party baas has staff employed for all the management and you just pay x to use their resources. You also have to add to this calculation that by depending on a third party service you may need to adapt your software over time to stay compatible with said service.

If you're just starting out and experimenting just relying on a third party service may be the cheapest (especially since some offer free tiers to lure people in). When you know what functionality you need and are confident in your technical choices it may become viable to move to your own backend.

**Comment by zionnite** [comment]
Sir, thanks for all effort.

Am enlighten, pls can I have your email, WhatsApp, Twitter.

I would like you to mentor me.

Am new to this approach, I basically use Apache Server, I want to up my skill.


Thanks

**Comment by fbartels** [comment]
I feel honored, but I am also just at the start of my journey with appwrite, so I am not quite sure how much help I can already be.

**Comment by stnguyen90** [comment]
@fbartels, thanks for the assistance! 

@zionnite, can this be closed now since no further action is required?

**Comment by zionnite** [comment]
@stnguyen90 

Thanks for contributing,
Please what are the minimum server requirements to work with appwrite.

Am thinking of purchasing my own VPs server

**Comment by eldadfux** [comment]
@zionnite you can learn more about min-requirements here: https://appwrite.io/docs/installation#systemRequirements

**Comment by zionnite** [comment]
> @zionnite you can learn more about min-requirements here: https://appwrite.io/docs/installation#systemRequirements

Thanks Bro
