### ISSUE TITLE
📚 Documentation: Sync/remember selected SDK

### ISSUE THREAD

**Issue by letsintegreat** [appwrite/docs#270]
### 💭 Description

Add a feature to sync the language or SDK preference for code snippets for the entire page.

Take [this page](https://appwrite.io/docs/databases) for example - I noticed that there are 5 code-snippets, and we can switch the SDK between 4 different options (Web, Flutter, Android, iOS)

But the thing is switching the SDK for one code-snippet won't alter other code-snippets. So, say I am working with the Flutter SDK, then I would have to change the SDK 5 times for this particular page.

Implement a feature to sync the preference across the entire page, if changed at one place.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by c99SRS** [comment]
HI @letsintegreat can you please tell me what needs to be done here? SO that I can work on

**Comment by Harini1023** [comment]
Hello!....@letsintegreat! I would be glad to work on this task and work according the the requirements provided

**Comment by stnguyen90** [comment]
Hi everyone 👋 Thanks for your interest, and thanks for raising the issue 🙏

Our team is aware of this and is already working on a solution internally. Since it's already being worked on, I will close this issue as it seems to track a lot of interest in contribution.

Anyone interested in contributing to Appwrite, please make sure to check out our [website](https://hacktoberfest.appwrite.io/), which links to a list of all Hacktoberfest contributions.

If you cannot find an issue you like, it's all good! You can look into our https://github.com/appwrite/appwrite/issues/4024 issue and drop a comment on what you would like to contribute.
